pipeline:
  build:
    image: node:10-alpine
    commands:
      - apk add --no-cache git
      - npm ci
      - NODE_ENV=production npm run build
      - npm run build:size
  now_prod:
    image: lucap/drone-now:latest
    pull: true
    deploy_name: face.camp
    type: static
    team: andyet
    alias: face.camp
    cleanup: true
    directory: build
    when:
      event: deployment
    secrets:
    - source: now_andyet_token
      target: now_token
  slack:
    image: plugins/slack
    username: drone
    channel: io-alerts
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
branches: master
