pipeline:
  build:
    image: node:8.11-alpine
    commands:
      - apk add --no-cache git
      - npm install
      - NODE_ENV=production npm run build
  now_prod:
    image: lucap/drone-now:latest
    pull: true
    deploy_name: face.camp
    type: static
    team: andyet
    alias: face.camp
    cleanup: true
    directory: build
    when:
      event: deployment
    secrets: [ now_token ]
  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    username: drone
    channel: alerts
branches: master
