pipeline:
  build:
    image: node:10-alpine
    commands:
      - apk add --no-cache git
      - npm ci
      - npm run lint:ci
      - npm test
      - NODE_ENV=production npm run build
      - npm run build:size
    when:
      event: [push, pull_request]
  now_prod:
    image: andyet/drone-now:latest
    pull: true
    deploy_name: face.camp
    type: static
    team: andyet
    alias: face.camp
    cleanup: true
    directory: build
    when:
      event: deployment
    secrets: [now_token]
  slack:
    image: andyet/drone-slack:stable
    username: drone
    pull: true
    channel: io-alerts
    secrets: [slack_webhook, github_access_token, github_slack_lookup]
    when:
      status: [success, failure]
